### ISSUE TITLE
URL can't contain control characters

### ISSUE THREAD

**Issue by debdrup** [fletchowns/awfulutils#10]
I managed to get a new error
```
Traceback (most recent call last):
  File "/usr/local/bin/awful_export_thread.py", line 33, in <module>
    awful_client.export_thread(args.threadid)
  File "/usr/local/lib/python3.7/site-packages/awfulutils/awfulclient.py", line 86, in export_thread
    thread_export.save()
  File "/usr/local/lib/python3.7/site-packages/awfulutils/awfulclient.py", line 167, in save
    data = future.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/awfulutils/awfulclient.py", line 201, in __save_page
    downloaded_images_count = self.__process_images(page_soup, page_number)
  File "/usr/local/lib/python3.7/site-packages/awfulutils/awfulclient.py", line 293, in __process_images
    with open(output_filename, 'wb') as output_file, self.opener.open(original_src) as response:
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1378, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.7/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1273, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.7/http/client.py", line 1116, in putrequest
    self._validate_path(url)
  File "/usr/local/lib/python3.7/http/client.py", line 1207, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/de28e6e57e891eb66aa0d111bc570c552d86bdac/michael cera- awkward 5.jpg' (found at least ' ')
```
It seems like a simple misparse, though?

**Comment by debdrup** [comment]
I just got this again:
```
Traceback (most recent call last):
  File "/usr/local/bin/awful_export_thread.py", line 33, in <module>
    awful_client.export_thread(args.threadid)
  File "/usr/local/lib/python3.7/site-packages/awfulutils/awfulclient.py", line 86, in export_thread
    thread_export.save()
  File "/usr/local/lib/python3.7/site-packages/awfulutils/awfulclient.py", line 167, in save
    data = future.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/awfulutils/awfulclient.py", line 201, in __save_page
    downloaded_images_count = self.__process_images(page_soup, page_number)
  File "/usr/local/lib/python3.7/site-packages/awfulutils/awfulclient.py", line 293, in __process_images
    with open(output_filename, 'wb') as output_file, self.opener.open(original_src) as response:
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1378, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.7/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1273, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.7/http/client.py", line 1116, in putrequest
    self._validate_path(url)
  File "/usr/local/lib/python3.7/http/client.py", line 1207, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/9c6ace3cdb26776d06de9b822b175ef0289c0dda/hidden movement.jpg' (found at least ' ')
```

Seems like it's trying to parse a space, but of course those can't be in URLs so I'm not sure how the space snuck in there, unless the webhost uses %20 for encoded URLs?
