### ISSUE TITLE
Error saving page..

### ISSUE THREAD

**Issue by debdrup** [fletchowns/awfulutils#9]
Occationally, while grabbing pages, it'll throw an error to stderr which looks something like this:
```
Starting page 32/453
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/awfulutils/awfulclient.py", line 166, in save
    data = future.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/awfulutils/awfulclient.py", line 201, in __save_page
    downloaded_images_count = self.__process_images(page_soup, page_number)
  File "/usr/local/lib/python3.7/site-packages/awfulutils/awfulclient.py", line 306, in __process_images
    with open(output_filename, 'wb') as output_file, self.opener.open(original_href) as response:
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/awful_export_thread.py", line 32, in <module>
    awful_client.export_thread(args.threadid)
  File "/usr/local/lib/python3.7/site-packages/awfulutils/awfulclient.py", line 85, in export_thread
    thread_export.save()
  File "/usr/local/lib/python3.7/site-packages/awfulutils/awfulclient.py", line 168, in save
    logger.exception('Error saving page %d' % page_number, e)
Message: 'Error saving page 32'
Arguments: (<HTTPError 404: 'Not Found'>,)
```

I've snipped out all the other threads that were running at the same time, but lemme know if you need a full log file, as I have that available.

As far as I can tell, it seems to coincide with those files ending up being 0 bytes big, so it's definitely something that needs a little TLC, if it's to be used for archiving.

**Comment by debdrup** [comment]
For the record, I think this is a great solution - it's just that it shouldn't produce zero-byte files. Better that an image is missing than a complete page is.

**Comment by debdrup** [comment]
I ran it on a big thread with ~450 pages, and [here is the log (with both stdin and stderr)](https://nullrouted.org/run.txt) and (here is the directory it produced)[https://nullrouted.org/ls.txt) - as you can see, there are some files which are 0 bytes. :(

**Comment by debdrup** [comment]
Well, I found out that if you just delete the zero-byte files and run it again, it'll do better!
So while the issue still exists, it can be mitigated that way.

**Comment by fletchowns** [comment]
Ok cool! Thanks for the detailed bug report. I think we may just need to add a retry when one of the pages fails, since it seems to be an intermittent thing as you mentioned. Should have a set of changes pushed soon for you to try out.

**Comment by fletchowns** [comment]
@debdrup pushed some changes that should address the issue. I think it was just missing an exception handler for external images, so it would cause the whole page to bomb out if an error was encountered downloading an external image. Lemme know how it goes!
